version: "3"
services:
  testing:
    image: metabase/metabase:latest
    container_name: testing-metabase
    restart: always
    ports:
      - 3005:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: ${DB_TYPE}
      MB_DB_DBNAME: ${DB_NAME_TESTING}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: ${DB_HOST}

  beta:
    image: metabase/metabase:latest
    container_name: beta-metabase
    restart: always
    ports:
      - 4000:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: ${DB_TYPE}
      MB_DB_DBNAME: ${DB_NAME_STAGING}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: ${DB_HOST}

  arms-stage:
    image: metabase/metabase:latest
    container_name: production-metabase
    restart: always
    ports:
      - 5000:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: ${DB_TYPE}
      MB_DB_DBNAME: ${DB_NAME_PRODUCTION}
      MB_DB_PORT: ${DB_PORT}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD_PRODUCTION}
      MB_DB_HOST: ${DB_HOST_PRODUCTION}
